version: '3.9'

services:
  web:
    image: nginx:latest
    ports:
      - '80:80'
    volumes:
      - ./../:/var/www/html
      - ./default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - php-network

  php-fpm:
    environment:
      PHP_IDE_CONFIG: "serverName=web"
      XDEBUG_IDEKEY: "PHPSTORM"
      XDEBUG_MODE: "debug"
      XDEBUG_SESSION: "xdebug_is_great"
      PHP_XDEBUG: "true"
    build:
      dockerfile: php-fpm/Dockerfile
#      context: php-fpm
    volumes:
      - ./../:/var/www/html
    networks:
      - php-network

networks:
  php-network:
    driver: bridge